-- Make email optional in guests table
ALTER TABLE public.guests ALTER COLUMN email DROP NOT NULL;

-- Seed guests list
INSERT INTO public.guests (full_name, email, expected_count)
VALUES
('Cécile RICHOU', NULL, 1),
('Fabrice RICHOU', NULL, 1),
('Christophe DOUGE', NULL, 1),
('Katia DOUGE', NULL, 1),
('Florence TRAHIN', NULL, 1),
('Xavier TRAHIN', NULL, 1),
('Pierre DOUGE', NULL, 1),
('Jibé TRAHIN', NULL, 1),
('Lauren TRAHIN', NULL, 1),
('Léo TRAHIN', NULL, 1),
('David TAYLOR', NULL, 1),
('Austin TAYLOR', NULL, 1),
('Amber TAYLOR', NULL, 1),
('Invité de David TAYLOR', NULL, 1),
('J-Pierre RICHOU', NULL, 1),
('Huguette RICHOU', NULL, 1),
('Alain TETREL', NULL, 1),
('Sylvie TETREL', NULL, 1),
('Marie CREPIN', NULL, 1),
('Fabrice CREPIN', NULL, 1),
('Patrice DOUGE', NULL, 1),
('Nadine DOUGE', NULL, 1),
('Elodie BESNARD', NULL, 1),
('François BESNARD', NULL, 1),
('Aurélien DOUGE', NULL, 1),
('Daniel PELLERIN', NULL, 1),
('Edouard PELLERIN', NULL, 1),
('Elise FRECHE', NULL, 1),
('Julien FRECHE', NULL, 1),
('Antoine PELLERIN', NULL, 1),
('Valérie DOUGE', NULL, 1),
('Thierry DOUGE', NULL, 1),
('Sophie DURAND', NULL, 1),
('Tony DURAND', NULL, 1),
('Sarah SCIMECA', NULL, 1),
('Jeremy SCIMECA', NULL, 1),
('Hugo DOUGE', NULL, 1),
('Invité de Hugo DOUGE', NULL, 1),
('Marie-denise DOUGE', NULL, 1),
('J-Claude TRAHIN', NULL, 1),
('Monique TRAHIN', NULL, 1),
('Sylvie TRESPEUCH', NULL, 1),
('Emilie TRESPEUCH', NULL, 1),
('Julien TRESPEUCH', NULL, 1),
('Julie TRESPEUCH', NULL, 1),
('Jordan TRESPEUCH', NULL, 1),
('Eric TRAHIN', NULL, 1),
('Manon TRAHIN', NULL, 1),
('Invité de Manon TRAHIN', NULL, 1),
('Tom TRAHIN', NULL, 1),
('Invité de Tom TRAHIN', NULL, 1),
('Jacqueline ESNAULT', NULL, 1),
('Cécile BACHE', NULL, 1),
('Steve BACHE', NULL, 1),
('Valentin AOUCHICHE', NULL, 1),
('Maxence BACHE', NULL, 1),
('Stacy NAPORA', NULL, 1),
('Fatima ESNAULT', NULL, 1),
('Ryan ESNAULT', NULL, 1),
('Lise DE WEVER', NULL, 1),
('Alexis DE WEVER', NULL, 1),
('Charlotte RIVAYRAND', NULL, 1),
('Antoine RIVAYRAND', NULL, 1),
('Paul CHARRUAU', NULL, 1),
('Mélanie LE GALLO LECCA', NULL, 1),
('Damien LE GALLO LECCA', NULL, 1),
('Victor LACOMBE', NULL, 1),
('Blanche LACOMBE', NULL, 1),
('Thibault ZIMMERMAN', NULL, 1),
('Camille ZIMMERMAN', NULL, 1),
('Bastien HARDY', NULL, 1),
('Pierre elie', NULL, 1),
('Charlotte CASAGRANDE', NULL, 1),
('Clément CASAGRANDE', NULL, 1),
('Mélanie LOIGEROT', NULL, 1),
('Martin LOIGEROT', NULL, 1),
('BN MARY', NULL, 1),
('Manon MARY', NULL, 1),
('Céline Catheline', NULL, 1),
('Adrien Catheline', NULL, 1),
('Julien Pares', NULL, 1),
('Lucie Pares', NULL, 1),
('Alioune DIOP', NULL, 1),
('Morgane DIOP', NULL, 1),
('Déborah DESAUNAY', NULL, 1),
('Raphael DESAUNAY', NULL, 1),
('Korentin', NULL, 1),
('Lily (jeune)', NULL, 1),
('Thomas', NULL, 1),
('Eléa (jeune)', NULL, 1),
('Maël HARDY', NULL, 1),
('Mathieu RIVAYRAND', NULL, 1),
('Marine RIVAYRAND', NULL, 1),
('Marion LIEBAULT', NULL, 1),
('Augustin LIEBAULT', NULL, 1),
('Hugo CHARRUAU', NULL, 1),
('Anna CHARRUAU', NULL, 1),
('Charles andré', NULL, 1),
('Ambre', NULL, 1),
('Laetitia GIN', NULL, 1),
('Alexandra BON', NULL, 1),
('Invité de Alexandra BON', NULL, 1),
('Adrien REBILLARD', NULL, 1),
('Invité de Adrien REBILLARD', NULL, 1),
('Frederique DURANTON', NULL, 1),
('Christophe Peck', NULL, 1),
('Emma CAMPS', NULL, 1),
('Invité de Emma CAMPS', NULL, 1),
('Juan ROJAS', NULL, 1),
('Didier CHALOUAS', NULL, 1),
('Carole CHALOUAS', NULL, 1),
('Françoise', NULL, 1),
('Lisa Delph', NULL, 1),
('David Delph', NULL, 1),
('François DE WEVER', NULL, 1),
('Katie DE WEVER', NULL, 1),
('Valérie DE WEVER', NULL, 1),
('Stéphane DE WEVER', NULL, 1),
('Claire ESNAULT', NULL, 1),
('Emmanuel ESNAULT', NULL, 1),
('J-louis LACOMBE', NULL, 1),
('Valentine LACOMBE', NULL, 1),
('Eloi LACOMBE', NULL, 1),
('Lucas ESNAULT', NULL, 1),
('Invité de Lucas ESNAULT', NULL, 1),
('Pierre ESNAULT', NULL, 1),
('Lois ESNAULT', NULL, 1),
('Eric CHARRUAU', NULL, 1),
('Invité de Eric CHARRUAU', NULL, 1),
('Cédric', NULL, 1),
('Virginie', NULL, 1),
('Marc', NULL, 1),
('Véronique', NULL, 1),
('Marc', NULL, 1),
('Isabelle', NULL, 1),
('DJ', NULL, 1);
